language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jarodsong/docker-react -f Dockerfile.dev .

script:
    docker run -e CI=true jarodsong/docker-react npm run test -- --coverage
